# SITE CONFIGURATION
baseurl: "/portfolio-jessica" # the subpath of your site, e.g. /blog/
url: "http://www.domain.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Jessica Appeldoorn
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Front-End Web Developer + Designer</h1>
     <p>I specialize in HTML, CSS, JavaScript & AngularJS</p>
  header_text_feature_image: 
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: jessica.appeldoorn@gmail.com
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: jessappeldoorn
  google_plus:
  instagram: 
  linkedin:  https://www.linkedin.com/in/jessicaappeldoorn
  pinterest: modapple
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: jessappeldoorn
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
